name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker login
      run: docker login docker.pkg.github.com --username utain
    - name: Build docker
      run: docker build -t docker.pkg.github.com/utain/spring-12factor-example/server:latest
    - name: Push docker image to github
      run: docker push docker.pkg.github.com/utain/spring-12factor-example/server:latest
